"""
intake.py

Support widget intake conversation handler.
Processes multi-turn conversations from the Django widget,
searches KB, enforces completeness gate, and creates tickets.
"""

import json
import re
from pathlib import Path

import anthropic

from agent import (
    fetch_crm_account,
    _run_auth_check,
    _run_auth_bypass,
)
from zoho_desk_api import (
    create_ticket as zoho_create_ticket,
    add_ticket_comment as zoho_add_comment,
    find_or_create_contact as zoho_find_or_create_contact,
    find_or_create_account as zoho_find_or_create_account,
)
from kb_search import (
    get_best_kb_match,
    check_and_create_kb_task,
    flag_stale_article,
)
from kb_sync import search_kb_articles
from slack_ticket_brief import send_ticket_brief

_client = anthropic.Anthropic()

INTAKE_PROMPT = (
    Path(__file__).parent / "intake_prompt.md"
).read_text(encoding="utf-8")

# Load Sam's Voice guide if it exists (generated by ticket_analyzer)
_voice_guide_path = (
    Path(__file__).parent / "knowledge_book" / "sams_voice.md"
)
if _voice_guide_path.exists():
    _voice_content = _voice_guide_path.read_text(encoding="utf-8")
    INTAKE_PROMPT += (
        "\n\n---\n\n"
        "## SAM'S VOICE (from real ticket analysis)\n\n"
        "The following style guide was generated from "
        "1000+ real support tickets handled by Sam. "
        "Mirror this tone and approach in all responses.\n\n"
        f"{_voice_content}"
    )

# Page path prefix -> module name mapping for auto-inference
_PAGE_MODULE_MAP = {
    "/admin/scheduling": "admin scheduling",
    "/admin/settings": "admin settings",
    "/admin/permissions": "admin permissions",
    "/admin/dashboard": "admin dashboard",
    "/opportunities": "opportunities",
    "/reserve": "reserve schedule",
    "/forms": "forms",
    "/groups": "groups",
    "/sites": "sites",
    "/kiosk": "kiosk",
    "/reports": "reports",
    "/chat": "chat",
    "/sequences": "sequences",
    "/hours": "hour tracking",
    "/kpi": "kpi dashboards",
    "/integrations": "integrations",
    "/categories": "categories",
    "/email": "email communications",
}

REQUIRED_FIELDS = {
    "affected_user_email": "Who is affected? Is this your own account or a specific volunteer's?",
    "module": "Which part of Vome is this about?",
    "description": "Can you describe what happened and what you expected to happen?",
    "platform": "Is this on web, mobile, or both?",
}


# ---------------------------------------------------------------------------
# Completeness gate
# ---------------------------------------------------------------------------

def check_completeness(
    extracted: dict,
    session_context: dict,
) -> tuple[bool, list[str]]:
    """Check if enough fields are present to create a ticket.

    Returns (is_complete, list_of_missing_field_names).
    Rule: 2+ missing = incomplete. 0-1 missing = complete (infer the rest).
    """
    missing = []

    for field in REQUIRED_FIELDS:
        val = extracted.get(field)
        if not val or val == "null":
            missing.append(field)

    # Auto-fill from session context where possible
    if "affected_user_email" in missing:
        # If user_role is admin and no volunteer mentioned, default to self
        if session_context.get("user_role") == "admin":
            pass  # Let Claude ask, but don't count as hard missing
    if extracted.get("affected_user_email") == "self":
        extracted["affected_user_email"] = session_context.get("user_email", "self")
        if "affected_user_email" in missing:
            missing.remove("affected_user_email")

    if "platform" in missing and session_context.get("platform"):
        extracted["platform"] = session_context["platform"]
        missing.remove("platform")

    if "module" in missing:
        inferred = _infer_module_from_page(session_context.get("current_page", ""))
        if inferred:
            extracted["module"] = inferred
            missing.remove("module")

    is_complete = len(missing) <= 1
    return is_complete, missing


def _infer_module_from_page(current_page: str) -> str | None:
    """Try to infer the module from the current page URL path."""
    if not current_page:
        return None
    page_lower = current_page.lower()
    for prefix, module in _PAGE_MODULE_MAP.items():
        if page_lower.startswith(prefix):
            return module
    return None


# ---------------------------------------------------------------------------
# Message building
# ---------------------------------------------------------------------------

def _build_intake_messages(
    message: str,
    session_context: dict,
    conversation_history: list,
    attachments: list,
    kb_context: str | None = None,
    kb_searched_no_results: bool = False,
) -> list[dict]:
    """Build the Claude messages array from conversation history + new message."""
    messages = []

    # Replay conversation history as alternating user/assistant turns
    for turn in conversation_history:
        role = turn.get("role", "user")
        content = turn.get("content", "")
        if role in ("user", "assistant") and content:
            messages.append({"role": role, "content": content})

    # Build the new user message with context
    user_content = message

    # Inject session context on first turn
    if not conversation_history:
        ctx_lines = []
        for key in ("user_email", "user_role", "org_name", "tier", "current_page", "platform"):
            val = session_context.get(key)
            if val:
                ctx_lines.append(f"{key}: {val}")
        if ctx_lines:
            user_content = (
                f"[Session context: {', '.join(ctx_lines)}]\n\n"
                f"{message}"
            )

    # Include attachment info
    if attachments:
        att_note = f"\n\n[User attached {len(attachments)} file(s): {', '.join(attachments)}]"
        user_content += att_note

    # Include KB search results if available
    if kb_context:
        user_content += f"\n\n[KB search results: {kb_context}]"
    elif kb_searched_no_results:
        user_content += (
            "\n\n[KB was already searched for this message and "
            "returned no relevant articles. Do NOT tell the user "
            "'let me search' — the search is already done. "
            "Proceed directly to either answering with what you "
            "know, asking a targeted follow-up, or collecting "
            "ticket info.]"
        )

    messages.append({"role": "user", "content": user_content})

    return messages


def _build_system_prompt(session_context: dict) -> str:
    """Build the system prompt with session context summary."""
    return INTAKE_PROMPT


# ---------------------------------------------------------------------------
# Response parsing
# ---------------------------------------------------------------------------

def _parse_intake_response(response_text: str) -> tuple[str, dict]:
    """Split Claude's response into reply text and structured JSON.

    Returns (reply_text, parsed_json).
    The JSON block is expected at the end of the response in a fenced block.
    """
    # Find the last ```json ... ``` block
    pattern = r"```json\s*\n(.*?)\n\s*```"
    matches = list(re.finditer(pattern, response_text, re.DOTALL))

    if not matches:
        # No JSON block found -- return full text with defaults
        return response_text.strip(), {
            "status": "collecting",
            "extracted": {
                "affected_user_email": None,
                "module": None,
                "platform": None,
                "description": None,
            },
            "kb_query": None,
            "issue_fingerprint": None,
        }

    last_match = matches[-1]
    json_str = last_match.group(1)

    # Reply text is everything before the JSON block
    reply_text = response_text[:last_match.start()].strip()

    try:
        parsed = json.loads(json_str)
    except json.JSONDecodeError:
        parsed = {
            "status": "collecting",
            "extracted": {},
            "kb_query": None,
            "issue_fingerprint": None,
        }

    # Ensure extracted has all expected keys
    extracted = parsed.get("extracted", {})
    for key in ("affected_user_email", "module", "platform", "description"):
        if key not in extracted:
            extracted[key] = None
    parsed["extracted"] = extracted

    return reply_text, parsed


# ---------------------------------------------------------------------------
# Ticket formatting
# ---------------------------------------------------------------------------

def _generate_ticket_subject(
    description: str,
    conversation_history: list,
) -> str:
    """Generate a concise ticket subject from the conversation.

    Uses Claude to produce a clean, short title that describes
    the issue without including org names or user details.
    """
    # Collect only the user messages for context
    user_msgs = [
        t.get("content", "")
        for t in conversation_history
        if t.get("role") == "user" and t.get("content")
    ]
    context = "\n".join(user_msgs) if user_msgs else description

    try:
        response = _client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=60,
            messages=[{
                "role": "user",
                "content": (
                    "Write a short ticket subject line (under 80 chars) "
                    "for this support issue. Be specific about the "
                    "problem. Do NOT include organization names, "
                    "user names, or emails. Just describe the bug "
                    "or request.\n\n"
                    f"{context[:500]}"
                ),
            }],
        )
        subject = response.content[0].text.strip()
        # Remove any quotes Claude might wrap it in
        subject = subject.strip('"').strip("'")
        if len(subject) > 120:
            subject = subject[:117] + "..."
        return subject
    except Exception as e:
        print(f"[INTAKE] Subject generation failed: {e}")
        # Fallback: use first user message, truncated
        fallback = user_msgs[0] if user_msgs else description
        if fallback and len(fallback) > 80:
            fallback = fallback[:77] + "..."
        return fallback or "Support request via widget"


def _build_ticket_html(
    conversation_history: list,
    attachments: list,
) -> str:
    """Build a clean HTML ticket body for Zoho Desk.

    The body is the conversation transcript only — structured metadata
    (module, platform, affected user, etc.) is posted as an internal
    comment so the ticket description stays focused on the customer
    exchange that the agent will reply to.
    """
    html = ""
    for turn in conversation_history:
        role = turn.get("role", "user")
        content = turn.get("content", "")
        if not content:
            continue

        if role == "user":
            label = "Customer"
            color = "#1a73e8"
        else:
            label = "Vic"
            color = "#666"

        html += (
            f"<div style='margin-bottom:12px;'>"
            f"<b style='color:{color};'>{label}</b><br>"
            f"<span>{_escape_html(content)}</span>"
            f"</div>"
        )

    if attachments:
        att_links = ", ".join(
            f"<a href='{a}'>{a.split('/')[-1]}</a>"
            for a in attachments
        )
        html += (
            f"<p><b>Attachments:</b> {att_links}</p>"
        )

    html += (
        "<hr style='border:none;border-top:1px solid #ddd;'>"
        "<p style='color:#999;font-size:11px;'>"
        "Submitted via Support Widget</p>"
    )

    return html


def _escape_html(text: str) -> str:
    """Basic HTML escaping."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\n", "<br>")
    )


# ---------------------------------------------------------------------------
# Ticket creation
# ---------------------------------------------------------------------------

def _create_ticket_from_intake(
    extracted: dict,
    session_context: dict,
    conversation_history: list,
    attachments: list,
) -> dict:
    """Create a Zoho Desk ticket + ClickUp task from the completed intake.

    Returns {"ticket_created": bool, "ticket_id": str | None}.
    """
    user_email = session_context.get("user_email", "")
    org_name = session_context.get("org_name", "")
    description = extracted.get("description", "No description provided")
    module = extracted.get("module", "other")
    platform = extracted.get("platform", session_context.get("platform", "web"))
    affected_email = extracted.get("affected_user_email", user_email)

    # Generate a clean ticket subject via Claude
    subject = _generate_ticket_subject(
        description, conversation_history,
    )

    # Create Zoho Desk ticket via direct REST API
    final_email = (
        affected_email if affected_email and affected_email != "self"
        else user_email
    )

    # Build a clean HTML body for the ticket (transcript only —
    # metadata is added as an internal comment below)
    ticket_description = _build_ticket_html(
        conversation_history=conversation_history,
        attachments=attachments,
    )

    # Resolve Zoho Desk account + contact so the ticket is
    # properly linked for search and client history.
    account_id = None
    contact_id = None

    if org_name:
        account = zoho_find_or_create_account(org_name)
        if account:
            account_id = str(account.get("id", ""))

    contact = zoho_find_or_create_contact(
        email=final_email,
        first_name=session_context.get("user_first_name", ""),
        last_name=session_context.get("user_last_name", ""),
        account_id=account_id,
    )
    if contact:
        contact_id = str(contact.get("id", ""))

    print(
        f"[INTAKE] Creating Zoho ticket for {final_email} "
        f"(contact={contact_id}, account={account_id}) "
        f"-- subject: {subject[:80]}"
    )
    ticket_data_raw = zoho_create_ticket(
        subject=subject,
        description=ticket_description,
        email=final_email,
        contact_id=contact_id,
        account_id=account_id,
    )

    if not ticket_data_raw or not isinstance(ticket_data_raw, dict):
        print(f"[INTAKE] Failed to create Zoho ticket.")
        return {"ticket_created": False, "ticket_id": None}

    ticket_id = str(ticket_data_raw.get("id", ""))
    ticket_number = str(
        ticket_data_raw.get("ticketNumber", "")
    )

    if not ticket_id:
        print(
            f"[INTAKE] Zoho ticket creation returned no ID. "
            f"Response: {ticket_data_raw}"
        )
        return {"ticket_created": False, "ticket_id": None}

    print(
        f"[INTAKE] Zoho ticket created: "
        f"#{ticket_number} (ID: {ticket_id})"
    )

    # Attach files if any
    # (Attachments are S3 URLs -- Zoho will need them linked, but for now
    #  we include them in the description. Full attachment API integration
    #  can be added later.)

    # CRM enrichment
    crm = fetch_crm_account(user_email)

    # Build ticket_data dict for ClickUp task creation
    ticket_data = {
        "ticket_id": ticket_id,
        "ticket_number": ticket_number,
        "subject": subject,
        "body": description,
        "contact_email": user_email,
        "contact_name": "",  # Not always available from widget
    }

    # Build agent_response string for ClickUp parsing
    # Format it in the way _parse_agent_response expects
    agent_response = (
        f"CLASSIFICATION: Bug\n"
        f"MODULE: {module}\n"
        f"PLATFORM: {platform}\n"
        f"PRIORITY: P3\n"
        f"ISSUE SUMMARY: {description}\n"
        f"SUGGESTED OWNER: Backend\n"
    )

    # Use analysis-based routing for ClickUp
    analysis = {
        "category": "bug",  # Default; could be refined with a classification call
        "complexity": "medium",
        "client_tier": _map_tier_to_score(session_context.get("tier", "")),
        "engineer_type": "backend",
    }

    zoho_url = f"https://desk.zoho.com/agent/vomevolunteer/tickets/{ticket_id}"

    # Note: ClickUp task creation is intentionally NOT triggered here.
    # New widget tickets land in Zoho with status "New" for human triage
    # first. A ClickUp task is only created once a ticket is assigned to
    # the backend or frontend team — handled out-of-band, not from intake.

    # Post Slack ticket brief
    try:
        send_ticket_brief(
            ticket_id=ticket_id,
            ticket_number=ticket_number,
            subject=subject,
            crm=crm,
            agent_response=agent_response,
            clickup_task_url=None,
            zoho_ticket_url=zoho_url,
            clickup_task_id=None,
            contact_email=user_email,
            issue_summary=description,
            new_classification=analysis,
        )
    except Exception as e:
        print(f"[INTAKE] Slack brief failed: {e}")

    # Post internal note on Zoho ticket (direct API)
    try:
        note = (
            f"Ticket created via Support Widget\n\n"
            f"Module: {module}\n"
            f"Platform: {platform}\n"
            f"Affected user: {affected_email}\n"
            f"Org: {org_name} "
            f"({session_context.get('tier', 'unknown')} tier)\n"
            f"Source page: "
            f"{session_context.get('current_page', 'unknown')}\n"
        )
        if attachments:
            note += f"\nAttachments: {', '.join(attachments)}\n"
        zoho_add_comment(ticket_id, note)
    except Exception as e:
        print(f"[INTAKE] Internal note failed: {e}")

    return {"ticket_created": True, "ticket_id": ticket_id}


def _map_tier_to_score(tier: str) -> str:
    """Map plan tier name to the client_tier scoring label."""
    tier_lower = (tier or "").strip().lower()
    tier_map = {
        "ultimate": "very-high",
        "enterprise": "high",
        "pro": "medium",
        "recruit": "low",
    }
    return tier_map.get(tier_lower, "low")


# ---------------------------------------------------------------------------
# Main orchestrator
# ---------------------------------------------------------------------------

def run_intake_turn(
    message: str,
    session_context: dict,
    conversation_history: list,
    attachments: list | None = None,
) -> dict:
    """Process one turn of the intake conversation.

    Returns the response dict to send back to Django:
    {
        "reply": str,
        "status": "collecting" | "deflecting" | "confirming" | "complete",
        "kb_article": {...} | None,
        "ticket_created": bool,
        "ticket_id": str | None,
    }
    """
    attachments = attachments or []

    # Step 1: Run Claude to get the conversational reply + structured data
    kb_context = None
    kb_article_response = None

    # Check if previous turn had a kb_query we should search
    # (We look at the last assistant message's JSON block)
    prior_kb_query = _extract_prior_kb_query(conversation_history)
    if prior_kb_query:
        kb_match = _search_kb_combined(
            prior_kb_query,
            session_context.get("locale"),
        )
        if kb_match:
            kb_context = json.dumps(kb_match)
            kb_article_response = {
                "title": kb_match["title"],
                "url": kb_match["url"],
                "days_stale": kb_match["days_stale"],
            }

    # Upfront KB search: run on the raw user message so Claude has
    # KB results available on the very first turn (instead of waiting
    # for Claude to emit a kb_query that only gets searched next turn).
    kb_searched_no_results = False
    if not kb_context and not prior_kb_query and message.strip():
        upfront_match = _search_kb_combined(
            message.strip(),
            session_context.get("locale"),
        )
        if upfront_match:
            if upfront_match["action"] == "flag_stale":
                flag_stale_article(upfront_match)
                kb_searched_no_results = True
            else:
                kb_context = json.dumps(upfront_match)
                kb_article_response = {
                    "title": upfront_match["title"],
                    "url": upfront_match["url"],
                    "days_stale": upfront_match["days_stale"],
                }
        else:
            kb_searched_no_results = True

    messages = _build_intake_messages(
        message=message,
        session_context=session_context,
        conversation_history=conversation_history,
        attachments=attachments,
        kb_context=kb_context,
        kb_searched_no_results=kb_searched_no_results,
    )

    system_prompt = _build_system_prompt(session_context)

    try:
        response = _client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=1024,
            system=system_prompt,
            messages=messages,
        )
        response_text = response.content[0].text
    except Exception as e:
        print(f"[INTAKE] Claude call failed: {e}")
        return {
            "reply": "I'm having trouble processing your request right now. Please try again in a moment.",
            "status": "collecting",
            "kb_article": None,
            "ticket_created": False,
            "ticket_id": None,
        }

    # Step 2: Parse the response
    reply_text, parsed = _parse_intake_response(response_text)
    extracted = parsed.get("extracted", {})
    status = parsed.get("status", "collecting")
    kb_query = parsed.get("kb_query")
    issue_fingerprint = parsed.get("issue_fingerprint")
    auth_check_email = parsed.get("auth_check")

    # Step 2b: Handle auth check if Claude requested one
    if auth_check_email:
        auth_result = _run_auth_check(auth_check_email)
        if auth_result:
            # If bypassable, auto-activate
            if auth_result.get("is_bypassable"):
                bypass_result = _run_auth_bypass(auth_check_email)
                if bypass_result and bypass_result.get("bypassed"):
                    reply_text += (
                        "\n\nI've activated your account. "
                        "You should be able to log in now! "
                        "If you have any trouble, try resetting "
                        "your password here: "
                        "https://www.vomevolunteer.com/forgot"
                    )
                    status = "complete"
            elif auth_result.get("is_active"):
                reply_text += (
                    "\n\nI can see your account is already "
                    "active. Try resetting your password here: "
                    "https://www.vomevolunteer.com/forgot"
                )
            elif not auth_result.get("found"):
                reply_text += (
                    "\n\nI couldn't find an account with that "
                    "email. You may need to register first: "
                    "https://www.vomevolunteer.com/register-volunteer"
                )

    # Step 3: If this is the first turn and Claude generated a kb_query, search now
    if kb_query and not prior_kb_query and not kb_article_response:
        kb_match = _search_kb_combined(
            kb_query,
            session_context.get("locale"),
        )
        if kb_match:
            kb_article_response = {
                "title": kb_match["title"],
                "url": kb_match["url"],
                "days_stale": kb_match["days_stale"],
            }
            # If stale, flag it
            if kb_match["action"] == "flag_stale":
                flag_stale_article(kb_match)
                kb_article_response = None  # Don't show stale articles

    # Step 4: Apply completeness gate
    is_complete, missing = check_completeness(extracted, session_context)

    # Override status based on completeness
    if status == "complete":
        # User confirmed -- create the ticket
        ticket_result = _create_ticket_from_intake(
            extracted=extracted,
            session_context=session_context,
            conversation_history=conversation_history,
            attachments=attachments,
        )

        # Log unmatched issue for KB gap tracking
        if issue_fingerprint and not kb_article_response:
            check_and_create_kb_task(
                fingerprint=issue_fingerprint,
                org_id=session_context.get("org_id"),
                user_email=session_context.get("user_email"),
            )

        # If ticket creation failed, override Claude's optimistic reply
        if not ticket_result.get("ticket_created"):
            print(
                f"[INTAKE] Ticket creation failed for "
                f"{session_context.get('user_email')} — "
                f"overriding reply text"
            )
            reply_text = (
                "I'm sorry, I wasn't able to create your ticket "
                "right now due to a system issue. Your conversation "
                "has been saved — please try again in a few minutes, "
                "or email us at support@vomevolunteer.zohodesk.com "
                "and we'll follow up with you."
            )

        return {
            "reply": reply_text,
            "status": "complete",
            "kb_article": kb_article_response,
            "ticket_created": ticket_result.get("ticket_created", False),
            "ticket_id": ticket_result.get("ticket_id"),
        }

    elif status == "confirming" and not is_complete:
        # Claude thinks we're ready but completeness gate says no.
        # Exception: if we have at least a description, allow it
        # through (frustrated user early exit -- Claude detected
        # frustration and is wrapping up with what it has).
        has_description = bool(
            extracted.get("description")
        )
        if not has_description:
            status = "collecting"

    # Log unmatched issues on each turn where we have a fingerprint
    if issue_fingerprint and not kb_article_response and status not in ("deflecting",):
        check_and_create_kb_task(
            fingerprint=issue_fingerprint,
            org_id=session_context.get("org_id"),
            user_email=session_context.get("user_email"),
        )

    return {
        "reply": reply_text,
        "status": status,
        "kb_article": kb_article_response,
        "ticket_created": False,
        "ticket_id": None,
    }


def _extract_prior_kb_query(conversation_history: list) -> str | None:
    """Extract the kb_query from the last assistant message's JSON block."""
    for turn in reversed(conversation_history):
        if turn.get("role") == "assistant":
            content = turn.get("content", "")
            _, parsed = _parse_intake_response(content)
            return parsed.get("kb_query")
    return None


def _search_kb_combined(
    query: str,
    locale: str | None = None,
) -> dict | None:
    """Search KB using ChromaDB first (semantic), fall back to Zoho API (keyword).

    Returns a dict with {title, url, days_stale, action} or None.
    """
    # Try ChromaDB (nightly-indexed articles)
    try:
        chroma_results = search_kb_articles(
            query, n_results=1, language=locale,
        )
        if chroma_results:
            best = chroma_results[0]
            # Only use if relevance score is reasonable
            if best.get("score") and best["score"] > 0.3:
                days = best.get("days_stale")
                if days is not None and days > 365:
                    action = "flag_stale"
                elif days is not None and days > 90:
                    action = "suggest_with_caveat"
                else:
                    action = "suggest"
                return {
                    "title": best["title"],
                    "url": best["url"],
                    "days_stale": days,
                    "action": action,
                }
    except Exception as e:
        print(f"[KB] ChromaDB search failed, falling back: {e}")

    # Fall back to Zoho keyword search
    return get_best_kb_match(query)
