"""
setup_guide.py

Turns the Vome Setup Guide into always-on knowledge for Vic.

The guide lives in two places and neither is complete on its own:

  * vome-react holds the substance. Seven stages in order, 45 sections,
    the decisions each one settles and 112 tips and warnings, all
    hardcoded in setupGuideContent.js and translations/postlogin.js.
    None of it is in Zoho, so none of it ever reached the agent.
  * The help center holds the 45 articles the guide links to for detail.
    kb_sync already indexes those, so full-text search can surface one
    when a question matches its wording.

Neither path covered the case that matters most. An admin asking "we are
just getting started, where do we begin" matches no article well, and
the guide's own advice was invisible. So this builds a `setup_guide`
section that knowledge.py carries on every prompt: the path, what each
stage settles, the traps, and which article to link for the detail.

Deliberately a map rather than a copy. The source digest runs to about
80,000 characters, which cannot ride on every draft, and the articles
are already retrievable on demand. The section's job is to let Vic place
where someone is and point at the right thing.

Source of truth is knowledge_book/setup_guide_source.json, regenerated by
scripts/sync_setup_guide.py whenever the in-app guide changes.

    python scripts/sync_setup_guide.py   # refresh the source digest
    python setup_guide.py                # rebuild the knowledge section
    python setup_guide.py --preview      # show what would be sent
"""

import json
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

import anthropic

from database import get_kb_articles_by_permalink_prefix
from model_config import SUPPORT_MODEL
import knowledge_synthesis as ks

if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

_client = anthropic.Anthropic()

SECTION_KEY = "setup_guide"
SECTION_TITLE = "Setting up Vome: the path and the decisions"

SOURCE_JSON = (
    Path(__file__).parent / "knowledge_book" / "setup_guide_source.json"
)

# Budget for the finished section, in characters. It rides on every
# draft alongside the voice guide, so it stays a map.
SECTION_MAX_CHARS = 9000

HELP_CENTER = "https://support.vomevolunteer.com/portal/en/kb/articles"


def load_source() -> dict | None:
    """Load the digest produced by scripts/sync_setup_guide.py."""
    if not SOURCE_JSON.exists():
        print(
            f"[SETUP GUIDE] {SOURCE_JSON.name} missing. Run "
            f"`python scripts/sync_setup_guide.py` first."
        )
        return None
    try:
        return json.loads(SOURCE_JSON.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"[SETUP GUIDE] Could not read source digest: {e}")
        return None


def resolve_article_urls(slugs: list[str]) -> dict[str, str]:
    """Map article slug to its real help center URL via the synced index.

    Falls back to the canonical URL shape for any slug the index has not
    caught up with, so a freshly published article still gets a link
    rather than being dropped.
    """
    urls: dict[str, str] = {}
    try:
        indexed = get_kb_articles_by_permalink_prefix(
            list({s for s in slugs}), language="en", limit=500
        )
        for article in indexed:
            if article["permalink"]:
                urls[article["permalink"]] = article["url"]
    except Exception as e:
        print(f"[SETUP GUIDE] URL lookup failed, using canonical form: {e}")

    missing = [s for s in slugs if s not in urls]
    for slug in missing:
        urls[slug] = f"{HELP_CENTER}/{slug}"
    if missing:
        print(
            f"[SETUP GUIDE] {len(missing)} linked article(s) not yet in the "
            f"index, using canonical URLs: {', '.join(missing[:5])}"
            + (" ..." if len(missing) > 5 else "")
        )
    return urls


def build_stage_blocks(data: dict, urls: dict[str, str]) -> list[str]:
    """One text block per stage, for synthesis."""
    blocks = []
    for i, stage in enumerate(data.get("stages", []), start=1):
        lines = [f"STAGE {i} of 7: {stage['label']}"]
        for section in stage.get("sections", []):
            lines.append("")
            lines.append(f"  SECTION: {section['title']}")
            if section.get("intro"):
                lines.append(f"  Why it matters: {section['intro']}")
            for point in section.get("prompts", []):
                lines.append(f"  - {point}")
            for tip in section.get("advice", []):
                lines.append(f"  TIP: {tip}")
            for slug in section.get("articles", []):
                lines.append(f"  ARTICLE: {slug} -> {urls.get(slug, '')}")
        blocks.append("\n".join(lines))
    return blocks


# ---------------------------------------------------------------------
# Synthesis
# ---------------------------------------------------------------------

# Fidelity matters more here than in the learned sections. Those
# synthesise patterns out of noisy ticket data, where generalising is
# the point. This is edited guidance a human wrote, so the job is to
# compress it without inventing.
_RULES = """Rules, in order of importance:
- Every statement must come from the material above. Do not add setup advice of your own, however sensible it sounds.
- Reproduce article URLs exactly as given. They are how the agent links a client to the detail.
- Keep the stage ordering. The sequence is the most useful thing here.
- Keep points concrete. "Decide whether people apply through a form or straight to an opportunity" beats "consider your application flow".
- Compress hard. This rides on every drafted reply, so it is a map, not a copy. Detail lives in the linked articles.
- No em dashes."""

_STRUCTURE = """1. **The path** -- the seven stages in order, one line each, saying what each settles
2. **Per stage** -- the decisions that matter, the traps, and the article URLs to link
3. **Ordering traps** -- where doing one stage before another causes rework
4. **Placing an admin** -- the questions that identify which stage someone is stuck on"""

DIRECT_PROMPT = """You are writing the "Setting up Vome" section of the support knowledge book, from the in-app Setup Guide below. A support agent reads it before answering an admin who is setting up or restructuring their organization.

{articles}

Write a section with:

{structure}

{rules}

Write in markdown. Keep it under {max_words} words."""

MAP_PROMPT = """You are condensing the Vome Setup Guide, stage batch {index} of {total}. A later pass merges every batch into one section.

{articles}

For each stage and section, output terse notes covering:
- What the stage settles, in one line
- The decisions that actually change how the setup is built
- Traps: anything that causes rework if done in the wrong order
- The article URLs, exactly as given

{rules}

Return only the notes, no preamble."""

REDUCE_PROMPT = """You are writing the "Setting up Vome" section of the support knowledge book, merging notes from {batch_count} batches of the in-app Setup Guide.

{notes}

Write a section with:

{structure}

{rules}

Write in markdown. Keep it under {max_words} words."""


def build_section_content(blocks: list[str]) -> str | None:
    """Synthesise the section. None if every Claude call failed."""
    if not blocks:
        return None
    max_words = SECTION_MAX_CHARS // 6

    return ks.map_reduce_section(
        blocks,
        section_title=SECTION_TITLE,
        direct_prompt=lambda joined: DIRECT_PROMPT.format(
            articles=joined, rules=_RULES, structure=_STRUCTURE,
            max_words=max_words,
        ),
        map_prompt=lambda joined, i, n: MAP_PROMPT.format(
            articles=joined, index=i, total=n, rules=_RULES,
        ),
        reduce_prompt=lambda notes, batches: REDUCE_PROMPT.format(
            notes=notes, batch_count=batches, rules=_RULES,
            structure=_STRUCTURE, max_words=max_words,
        ),
        client=_client,
        model=SUPPORT_MODEL,
        delay=2.0,
    )


def generate_setup_guide_section() -> int:
    """Rebuild the setup_guide knowledge section. Returns section count."""
    data = load_source()
    if not data:
        return 0

    stages = data.get("stages", [])
    slugs = data.get("all_article_slugs", [])
    sections = sum(len(s.get("sections", [])) for s in stages)
    if not stages:
        print("[SETUP GUIDE] Source digest has no stages")
        return 0

    print(
        f"[SETUP GUIDE] Building from {len(stages)} stages, "
        f"{sections} sections, {len(slugs)} linked articles "
        f"(source generated {data.get('generated', '?')})"
    )

    urls = resolve_article_urls(slugs)
    content = build_section_content(build_stage_blocks(data, urls))
    if not content:
        print("[SETUP GUIDE] Synthesis failed")
        return 0

    from ticket_analyzer import _save_knowledge_section

    header = (
        f"*Condensed from the in-app Setup Guide: {len(stages)} stages, "
        f"{sections} sections, {len(slugs)} linked help center articles. "
        f"Source generated {data.get('generated', '?')}. Link the article "
        f"URLs for detail rather than reproducing them.*"
    )
    _save_knowledge_section(
        SECTION_KEY, SECTION_TITLE, f"{header}\n\n{content}", sections
    )
    print(f"[SETUP GUIDE] Written: {SECTION_KEY} ({sections} sections)")

    try:
        import knowledge
        knowledge.clear_cache()
    except Exception as e:
        print(f"[SETUP GUIDE] Could not clear read cache: {e}")

    return sections


if __name__ == "__main__":
    if "--preview" in sys.argv:
        src = load_source()
        if src:
            blocks = build_stage_blocks(
                src, resolve_article_urls(src.get("all_article_slugs", []))
            )
            total = sum(len(b) for b in blocks)
            batches = ks.batch_summaries(blocks, ks.MAP_BATCH_CHARS)
            print(f"{len(blocks)} stage blocks, {total} chars, "
                  f"{len(batches)} batch(es)")
            print()
            print(blocks[0][:2000])
    else:
        generate_setup_guide_section()
